[package]
name = "rust-irc"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustirc"
path = "src/irc.rs"

[[bin]]
name = "ircbin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
